pub const KEYS: &[(&str, &str)] = &[
    ("j / k, ↓ / ↑, wheel", "Scroll one line"),
    ("Ctrl-d / Ctrl-u", "Half page down / up"),
    ("Ctrl-f / Ctrl-b, Space", "Page down / up"),
    ("g / G", "Top / bottom"),
    ("b / o", "Toggle the files / outline panel"),
    ("f", "Focus mode: hide the panels, full width"),
    ("Tab / Shift-Tab", "Cycle focus between the panes"),
    ("Tab then ← / →", "Move focus in that direction"),
    ("l", "Focus the pane to the right"),
    ("j / k in a panel", "Move, Enter opens or returns"),
    (
        "Space, ← / → in a panel",
        "Fold, collapse / expand a folder or section",
    ),
    ("- / = in a panel", "Fold all / unfold all"),
    ("T in the files panel", "Show titles instead of file names"),
    ("] / [", "Select the next / previous link"),
    ("Enter, click", "Follow the selected link"),
    ("H / L", "Back / forward through visited pages"),
    ("Ctrl-p", "Find a file in the folder"),
    ("E", "Edit the file in $EDITOR, reload on return"),
    ("/", "Search, Enter to keep, Esc to cancel"),
    ("n / N", "Next / previous match"),
    ("t", "Table of contents"),
    ("r", "Reload the file"),
    ("h, ?", "This help"),
    ("q", "Quit"),
];
